---
version: "3.7"

# This Docker composition file is used to build and test the container
# sudo docker-compose up --build --force-recreate 

secrets:
  fullchain_pem:
    file: ./src/secrets/fullchain.pem
  privkey_pem:
    file: ./src/secrets/privkey.pem
  users_txt:
    file: ./src/secrets/users.txt


services:
  postfix:
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: externalcoi/postfix
    init: true
    restart: always
    environment:
      - PRIMARY_DOMAIN=externalcoi.local
      - RELAY_IP=0.0.0.0/0
    networks:
      front:
        ipv4_address: 172.16.202.2
    ports:
      - target: "25"
        published: "1025"
        protocol: tcp
        mode: host
      - target: "587"
        published: "1587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "1993"
        protocol: tcp
        mode: host
    secrets:
      - source: fullchain_pem
        target: fullchain.pem
      - source: privkey_pem
        target: privkey.pem
      - source: users_txt
        target: users.txt

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24
